on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: rocklan/hello-world-composite-run-steps-action
        with:
          who-to-greet: 'Rocklan the legend'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
