on: [push]

jobs:
  cat_facts:
    runs-on: ubuntu-latest
    
    name: Display a cat fact
    
    steps:
      - uses: actions/checkout@v2
    
      - run: curl https://cat-fact.herokuapp.com/facts | jq .[2].text
        shell: bash


